### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by RomaricKc1**
Hello, 

I've added a translation for French.

### CODE REVIEW

**Comment by toasterofbread** [comment]
Not sure what's gone wrong with the builds, I'll fix that tomorrow

**Comment by RomaricKc1** [comment]
> Not sure what's gone wrong with the builds, I'll fix that tomorrow

It's my fault. I keep forgetting that `,`. I am not editing it in AS and don't have LSP support for `.kt`. I'll check the build if it fails again.

**Comment by toasterofbread** [comment]
Looks good, thanks!

**Comment by RomaricKc1** [comment]
> Looks good, thanks!

Merci!

**Pull request merged**
