### PR TITLE
 Add Chinese translation

### PR DESCRIPTION
**Pull request by ron159**
Hi,

This is a submission of simplified Chinese translations for review.

If possible, could you please provide a debug version? I will check and fix the translation accuracy based on the functionality.

Thank you!

### CODE REVIEW

**Comment by ron159** [comment]
@toasterofbread

**Comment by toasterofbread** [comment]
Thanks for the translation! 

Could you please add the external strings for Chinese as described on [this page](https://github.com/toasterofbread/spmp/wiki/App-localisation)?

**Comment by ron159** [comment]
> Thanks for the translation!
> 
> Could you please add the external strings for Chinese as described on [this page](https://github.com/toasterofbread/spmp/wiki/App-localisation)?

ok,will update as soon as possible

**Comment by toasterofbread** [comment]
Thanks!

**Pull request merged**
